### ISSUE TITLE
STMAS traps all attempts to open the MAS

### ISSUE THREAD

**Issue by Nimpoc** [lapcat/StopTheMacAppStore#2]
As of MacOS 12.5 I am no longer able to open the MAS through the Apple menu, as STMAS traps the launch. This is the same behavior as trapping a launch attempt from Safari.

When following an 'Open In' link from a Safari MAS Preview page, the 'Allow' button just leads to the STMAS dialogue window.

Clicking the 'Mac App Store' button within the STMAS.app also fails to launch the MAS.

Deleting STMAS was required to regain the ability to open MAS.

Please update to correct the behavior of this handy tool!

**Comment by lapcat** [comment]
I'm not seeing this happen on macOS 12.5.

STMAS doesn't even launch when I select the App Store... item in the  menu. This menu item just opens the App Store app directly.

Does it still happen if you re-install STMAS? If so, then what happens if you run these 2 commands in Terminal?

`open macappstore://apps.apple.com/app/stopthemadness/id1376402589`

`open -a "App Store" macappstore://apps.apple.com/app/stopthemadness/id1376402589`

**Comment by Nimpoc** [comment]
Hi Jeff,
Seems a removal / reinstall worked. I'm sorry that I didn't try that first.
I used AppCleaner to uninstall to try and make sure all dependencies were
deleted.

Keep up the good work. I thoroughly enjoy STM on both MacOS and iOS.

Mike
